//
//  Card.swift
//  FilmNite
//
//  Created by Sarah O'Brien on 11/25/20.
//

import Foundation
import UIKit
import Combine

//dummy data for now, figure out how to implement existing data
struct Card: Identifiable{
    let id = UUID()
    let name:String
    let imageName: String
    let released: String
    let bio: String


    var x: CGFloat = 0.0
    var y: CGFloat = 0.0
    var degree: Double = 0.0
    
    
    static var data: [Card]{
        [
            Card(name: "Hard Kill", imageName: "https://occ-0-1068-92.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaL51PPjWJ__DP3nSPEyfp2kW2xgNEUa4ImozcPwhTU9j0rAFr_513HHT9RmzjNIVR58kXPOTPvejRLYHH2UyecjiaHr5aDhD-_bJEZ88d1Cul2qdOn-y1ZAjfRquOEQWVEIoN1fnXGXjGz5wqfFWe682g.jpg?r=dcd", released: "2020", bio: "When a billionaire hires a team of mercenaries for protection, they soon realize world-changing technology and his daughter&rsquo;s life are also at stake."),
            Card(name: "The Call", imageName: "https://occ-0-1068-92.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWzWxE2i7VM29S25WeERIoc2IqewWndCGMRWsPT6IwBW1DJHkJ7tDTUqHFlVbJu2p4KLQER-qDqbG31K1S1GRMchkDaZ_hRclvwzl8w89Kd9EbBUt-fBLI4PDOM.jpg?r=ec6", released: "2020", bio: "Connected by phone in the same home but 20 years apart, a serial killer puts another woman&rsquo;s past &mdash; and life &mdash; on the line to change her own fate."),
            Card(name: "The Beast", imageName: "https://occ-0-1068-92.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQL49SvW6UgMvPpFMcR4-aSGxSJTzJ3J0MBcf2NmvVLdpUiBIoSMB6qzn0D_WjTD71EWuZG_8haws3fijSdTL5rfnxOAW3CqVO8xOVx6W7sA4JlXU8fgnZa3QPY.jpg?r=43a", released: "2020", bio: "To rescue his daughter, an unstable Special Forces veteran unleashes his inner beast as he pursues her kidnappers &acirc;&euro;&rdquo; and soon becomes a suspect himself."),
            Card(name: "Whose Streets?", imageName: "https://occ-0-1068-92.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABf1AbhZf8_HV_DQsz_2XtMLZtT9zexafLNQAnCeOLya3S8b_wPN8Gi3fqxhX0lCZiBKlgl61mtMkYj3XJ1yfrcL51A.jpg?r=901", released: "2017", bio: "Powered by activists and leaders, this documentary follows the rise of the Black Lives Matter movement following the 2014 killing of Michael Brown."),
            Card(name: "If Anything Happens I Love You", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYddZ9BSo3TYyo-lvrolQecZNcNgDNU2aGq-W-OhtJ_5JffFXEpwHTbq4eN70HQoSmy9X1Gh7hC7KajgilCCgbk7hSYL04th8KZfNIjIC-i01wQTIIjXdJaeOCE.jpg?r=c19", released: "2020", bio: "Grieving parents journey through an emotional void as they mourn the loss of a child in the aftermath of a tragic school shooting."),
            Card(name: "A Very Country Christmas", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcxmYZeH-dgH-urBcl47DWEVOgIuQwLIJSAE7QvhvFx9o_tV0gHQKBntFzorfjaAIitm3U9EI8TBeHLOi5G6y6Wpuw.jpg?r=cbc", released: "2017", bio: "When an unfulfilled country music star hides out in his hometown, he meets a budding interior designer who finds her way into his heart."),
            Card(name: "Hometown Holiday", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWYvoXsT_rZYdD53e7WM84wOy-y3ScrLxYjn7xlCSJsFAx1lZADjhPbU1Vk1JoGleQK1FJrPQgqZcHuEfeeqYaXqsA.jpg?r=835", released: "2018", bio: "An ambitious entertainment lawyer tries to sign a singing sensation in his sister&#39;s small town, but a local soon captures his attention &acirc;&euro;&rdquo; and heart."),
            Card(name: "Christmas with a Prince", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVAvZbv-FwJVZ3zu4v18RuUoFv7tjXgNXHLBLEkI_Ch1gaQvvd2qpqV9H3ehjWEe3rnXkBiGaNduWe686nEEpSk4IA.jpg?r=2a8", released: "2018", bio: "A dedicated pediatrician reconsiders her feelings for a carefree prince as he secretly recovers from a ski accident alongside her young patients."),
            Card(name: "The Outpost", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdPEAU1GD2fNgksXjObPUwog0UTlPiRswhYPo101Q5ovaO91StSa8pwcjPcR-OwXFPYmwKQfJvFtZ08TPQ2xuG4K9A.jpg?r=1fb", released: "2020", bio: "A group of vastly outnumbered U.S. soldiers at a remote Afghanistan base must fend off a brutal offensive by Taliban fighters in the Battle of Kamdesh."),
            Card(name: "Raising Victor Vargas", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVpR3pitomHvE1PZosGgU4cvmVAsgS-eMr0SsA6_InkW4Sg2bvHrh2V7gXBpOIvh0LHZjLNkKLPbsKKqyQRoM7rJsw.jpg?r=69d", released: "2002", bio: "A suave teen sets his sights on a girl who seems beyond his reach. But his game can&#39;t be confined to his tiny apartment and family&#39;s old-school values."),
            Card(name: "Tortilla Soup", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABf9ONjul1CA8cdCgGIH79hpu0ZcH7b9LfMMFhi5yO1MFxvKeRx9v14zK8XjPQaipYQ7nEl_qw2YugB7EzohBnNPSVg.jpg?r=dc2", released: "2001", bio: "Widower Martin is a restaurateur with a booming business and three headstrong daughters who leave the house to pursue their individual destinies."),
            Card(name: "Tremors: Shrieker Island", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXYvfysiGJ9gIehciWFcbdSF3ZOtwBunUL9iMoS2X7x7RwzfflY_fe1z2Var_INRlZ69GvENIL7jhN0zHy9pRNsjZg.jpg?r=5ac", released: "2020", bio: "When massive mutant creatures infiltrate an island nature preserve, scientists recruit a legendary monster hunter to battle the beasts."),
            Card(name: "Villain", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRlq93hvmRIK6aXw_nhQ_N5drMlpJMzwEcs7IwcbXzfOVo6PBzArENf03xyCUB1QpGz8WDkqqFkFu0on1tO9vHK_9A.jpg?r=982", released: "2020", bio: "Fresh out of prison, an ex-con tries to save his debt-ridden brother and the family pub until local mobsters draw him back to a criminal underworld."),
            Card(name: "Walk Away from Love", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcm_eQJ5ssS4IDPbs89RgatZDP1sxBMiPPCYRHYzGDZH6WXMFYhs0Nb_oZtAN01_4gSCqSc8L6xjm3SWchIpZK-mJQ.jpg?r=89d", released: "2017", bio: "Heartbroken from her last relationship, an attorney is wary of falling in love again. But crossing paths with an ex upends her plans to finally move on."),
            Card(name: "Yes, God, Yes", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQE9tPJ797SaECfsCXmKUUC48bIGZBZDLVDHGPu_94Pq65k26TBybz4iWdfq-08nIJQ9OIQI0OI08AeAKU_0bFxogw.jpg?r=c0a", released: "2020", bio: "A devoutly religious teen grapples with her own sexual awakening, and attends a Catholic school retreat in the hopes of suppressing her newfound urges."),
            Card(name: "I Am Vengeance: Retaliation", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSN-Himc6jhJML0W0THthA_HDHeXv1gFflYwaGZVlTdwGsAhk3blpY8E_77qXua14unOCXs7XGwl5-wmSwjJlDiklA.jpg?r=7a4", released: "2020", bio: "To clear his criminal record, an ex-special forces soldier agrees to lead a team to retrieve a double-crossing mercenary and deliver him to justice."),
            Card(name: "I Am Woman", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABV8xim3SV6ZlmsaQCothADnhA_6sCmBCAFr6K6pf_IXuxwgWC58tCiI1fhSbtuvnIsaeU7KuxENUMoqsEMMpMOb3xw.jpg?r=8dc", released: "2019", bio: "In the 1960s, Australian singer Helen Reddy struggles with misogyny in the music business &acirc;&euro;&rdquo; until she records an anthem for the women&#39;s movement."),
            Card(name: "The Hummingbird Project", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfb-YjYAgm6Dkie8J-e2fztJI5YDnqwwfe1YRRk-Pj5eKErY7k5XuRkbZhp7LWrCmCiI81mQTsXHqWhNMCkHMkamMQ.jpg?r=68f", released: "2018", bio: "After discovering a shortcut that gives them a technological advantage, two cousins look to earn their big score by outracing a massive corporation."),
            Card(name: "Fisherman&#39;s Friends", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTUlqWcFTUrRgf693yfyjtvl9vH0SzCNn3o0Grg4H2bl2WNYO6JbAZ9dk5NE9LpHgB9r7TavpFM-hh1OPlws0ij6hg.jpg?r=c84", released: "2019", bio: "Sea shanties have long united 10 Cornish fishermen, but when their chants sail to the music charts, their friendship is kept at bay."),
            Card(name: "Amandla! A Revolution in Four Part Harmony", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaU3-nqNZvpjVtSDM5jvzaDRUwrsAw7pm8u0l6frJhyBash_D74opyUHmM0BXt9zS9XXUiM5ruB89Iwl0ujgB-J-lw.jpg?r=b3d", released: "2002", bio: "This documentary recounts the fascinating and little-known role that music has played in the struggle to eradicate apartheid in South Africa."),
            Card(name: "Wheels of Fortune", imageName: "https://occ-0-1091-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABezYyKlXeDMY8BU68uAPWEj7o9lvQ9ZtJuTIpEf1zJMrM7wQQC-Xq87ZqWPdatYbCaal7KIY4RRlF8FxEdmmLTafTQ.jpg?r=514", released: "2020", bio: "To claim a big inheritance, a down-on-his-luck mechanic must win a series of competitions as outlined in his birth father&#39;s will."),
            Card(name: "Ghosts of War", imageName: "https://occ-0-1091-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABS_Qq2LjUyj6WgRmnc0llW68fqRlwPHQ3xr5Z-UY8Ouq-agXH2P0EDRLETR6FN-BIy38Igqc5-WTE9OKIn4r3yvYRg.jpg?r=45e", released: "2020", bio: "Five, battle-worn Allied soldiers guarding a chateau previously occupied by Nazis start experiencing unexplained and terrifying supernatural horrors."),
            Card(name: "His House", imageName: "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdqsVm3VIDwF3V6Bzz9Ic9deSrREAhZSmHT2HRbehhGHWG3WR5e-sH7BupNvvw4H_3LF8_Blki_4EVx22SxKK-ZfMQ_TSA6B6iQ1GzrvMa5_u4KuKcUYg39RiBk.jpg?r=61f", released: "2020", bio: "As a young couple from war-torn South Sudan seeks asylum and a fresh start in England, they&rsquo;re tormented by a sinister force living in their new home."),
            Card(name: "Holidate", imageName: "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdS2WN3tQ9fLz537aJX9EyqvPiUdGMnW4G9Uf-TDGCG6gPmlG_eikvufoUtMg73-HR8A2JXMJSAaGEMv-dUoGAPUBPNKQr3LF92FcC6JTfKhHMnX8YAmDYPd82FayTagOURNJYYvUBJ2DSrlUuH3iOOJXCBcJgerCE--RrLkeREl5SOdfA4EVQ.jpg?r=4d8", released: "2020", bio: "Fed up with being single on holidays, two strangers agree to be each other&#39;s platonic plus-ones all year long, only to catch real feelings along the way."),
            Card(name: "Over the Moon", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABY66fDJKkHCpkpvbtKUT0nBbMgHbjy9RImNeKwwENIUF3QYxsldZu_0UzLvC0JOYEh5O25uLumFPNb0xALpxndrMyj-ape0H7lVtmmcieEbWyFwcMWNWTlcDJdg.jpg?r=8e8", released: "2020", bio: "Fueled by memories of her mother, resourceful Fei Fei builds a rocket to the moon on a mission to prove the existence of a legendary moon goddess."),
            Card(name: "Cadaver", imageName: "https://occ-0-1091-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABW49eUyZN_PnLvPpzLwWe0702q-PfO5S2edTOXckHd0CgI8ZUX1hllQ09Rr_Cslfg0AUSwykyLvKF3SQp0Ar5kg0rwKawnRemSwKA5Qt10PVau5J9d8QXi_Z_Pc.jpg?r=ed9", released: "2020", bio: "When a peculiar hotel dinner show draws crowds during a postapocalyptic famine, one family discovers they&#39;ll pay much more than the price of admission."),
            Card(name: "Rebecca", imageName: "https://occ-0-2430-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQLCfPixMS_386AA3txJKNy7Cxz8cNriAFX1KlZOdaXmL4cwR9MLgHufVceTw_6yibLqta86O07R9neY0LGZiMmMo6NvghIKla0oO2bMNQXEB9Lo-cJip4iGP4M.jpg?r=d61", released: "2020", bio: "A young newlywed moves to her husband&#39;s imposing estate, where she must contend with his sinister housekeeper and the haunting shadow of his late wife."),
            Card(name: "Bending the Arc", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSxhaci83lldmBECq-TmBWTH3kyN5OvCx2s0JJyJ5ez3z7NHhV-kiuLBxwAp1ED3v_3Xah0cQyd8ALDIThge7JBwPw.jpg?r=fc2", released: "2017", bio: "This documentary follows a group of ambitious advocates whose mission to save lives in Haiti turns into a global fight for health care and justice."),
            Card(name: "The Trial of the Chicago 7", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcdnW6ld0KwcS4pAaIAWAPHgxlivaf7WPEiJswQTZlFMV6WPV-MCPyOJlpKrWMvQOaHeZpn4tvz-FBRUYe4sldQxP7mwRPW4fgCpbgsG_pYK5vvgUaq7eRuflKU.jpg?r=6c8", released: "2020", bio: "What was supposed to be a peaceful protest turned into a violent clash with the police. What followed was one of the most notorious trials in history."),
            Card(name: "Disconnect", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWfc4AtPZvUzTRkOmptuhphl_odUszUl1xnqFDAnMrW53D99sIm759CjxR7ufUxH5QOKOLE0OBErxu2Tn1sOHN__Lg.jpg?r=625", released: "2018", bio: "A group of singletons stumbles through the wild dating scene in Nairobi as two friends wonder if their relationship is more than platonic."),
            Card(name: "A Babysitter&#39;s Guide to Monster Hunting", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXxQXn8DJqBNMJsVBSXjK97mImvZ_a9IsFeZLIXFEFMumCC1-lA423wdh9dlH6wggKHGG1XVaFQosJDrUZ1CAsXRZYqYNDLLpl-9xkjV17Gtl3SWZhKLu7wPiUU.jpg?r=1c8", released: "2020", bio: "Recruited by a secret society of babysitters, a high schooler battles the Boogeyman and his monsters when they nab the boy she&#39;s watching on Halloween."),
            Card(name: "Octonauts &amp; the Great Barrier Reef", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUR-cawK125vgc0DCoklDt1biAAL9WjbwAVp4bMViWnYzCZ8lPYDeMoj7ZiphcCd_KdfxHqISUiF55sA3EyO18RgNoFvO3xQb4ySamDAxAJLQ4UEjq6tILComPQ.jpg?r=47a", released: "2020", bio: "In this musical special, the Octonauts must find a way to hold back hungry swarms of coral-eating starfish to save a new friend&rsquo;s fragile reef home."),
            Card(name: "The Forty-Year-Old Version", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbW1_LvvobvMQpn8_eioZX6P2xvBKP8sKzY6KjYV43pKpxyAUwmg59pWdP157BHRK4vWAFpEcERtbxOPW3B1Nw8r8kAbCN0rEMfix8QaHBatIpsEgnbQubED-5o.jpg?r=3c9", released: "2020", bio: "Desperate for a breakthrough as she nears the big 4-0, struggling New York City playwright Radha finds inspiration by reinventing herself as a rapper."),
            Card(name: "David Attenborough: A Life on Our Planet", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQKwvlqeKE03oXiZELV3K23Fok6otuf7X5ZLcBbNzYwiCs3ToKGfdUmTNccBZMpwReTFUq9AmpFJ3fFIhosz7BIz9NCRRjXobxm6AUcDhuNuadUme3HbA9hTTUI.jpg?r=c32", released: "2020", bio: "A broadcaster recounts his life, and the evolutionary history of life on Earth, to grieve the loss of wild places and offer a vision for the future."),
            Card(name: "The Binding", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVI4UcKhQFZa47N1aGsHpIOWfok3a3zcFJA21HlENcBJ2D31FVlp4pk0kVsNr6PrMIKViegYsiVXNQJ-UtLWYv1kyHff_UosttnJMbebfgMw-tcaelEVfrPJJnM.jpg?r=f00", released: "2020", bio: "While visiting her fianc&Atilde;&copy;&#39;s mother in southern Italy, a woman must fight the mysterious and malevolent curse intent on claiming her daughter."),
            Card(name: "You&#39;ve Got This", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXti893CmmuWYYAFHWJgZ4t_mj8FbbE2_dE0GTxxN3aaPWfUO36A8bclFuuO_XM0YzUjBujxerQeGLiVDuD4HiN0ppHN1Zx6iKDsTPZZbW-6fNTSgJ7cwE4PnUU.jpg?r=f85", released: "2020", bio: "An ad creative and a&nbsp;successful exec&nbsp;have a great marriage &mdash; until he wants to be a dad just as her star is rising. Then he brings someone new home."),
            Card(name: "Dick Johnson Is Dead", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZ4hzAxIwBc9VnUL3_RnZuf_0HxQ0Qq0-_Hh_Plp9xWacSBp_L76A7ixjwHOypHGbVzUy_5yRGnx0j-ILwhGH3dxWjk8PppCAcCeLx2WMLWs_g2-KWPxdB9ljXk.jpg?r=4f7", released: "2020", bio: "As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable."),
            Card(name: "The Boys in the Band", imageName: "https://occ-0-2430-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABc9TOIiMWY-zhg40ROdb2FvRNqTAyZM9GI9aVZGXOmjkMfXGx_q7ieddlYZ3Wb-mYs-gCkZgoDQvASbpsXSgrb4NPYdXYR5Msp001eI_pG3HdnR03oAeX7ltQUY.jpg?r=763", released: "2020", bio: "At a birthday party in 1968 New York, a surprise guest and a drunken game leave seven gay friends reckoning with unspoken feelings and buried truths."),
            Card(name: "A Love Song for Latasha", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQ7KGeqybVl9OW_VC_FiTw5_-0xu6UtsqK8565q1LU0-XkeAJi1lV7kvGIXI3_1YzHtxBVybodEEnQ_-tONiYzq4CB3ZhcbakLgFlp6mp52sHcEwPkistfSK-Gw.jpg?r=541", released: "2020", bio: "The killing of Latasha Harlins became a flashpoint for the 1992 LA uprising. This documentary evocatively explores the 15-year-old&#39;s life and dreams."),
            Card(name: "Residue", imageName: "https://occ-0-179-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXUoMNb_wZ87nqFs-NZMEz7q6yOuHeV_Qm37WqkU6cDCB5KVEE5EINjq4y4oYbKePWAQkVx68NMsSpTMgkCe26Mpaw.jpg?r=587", released: "2020", bio: "A young screenwriter returns to his hometown to write a script based on his childhood and discovers his neighborhood has been gentrified."),
            Card(name: "Horrid Henry&#39;s Gross Day Out", imageName: "https://occ-0-38-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWmlukFJU-mxfkE4xqdNqSek-e4xbo06QQL0Lv0WQxAA9hVG52cpjzI_-_NXWQCDl6cOYMY5cfxv4L_g6D4dZIAchw.jpg?r=075", released: "2020", bio: "Worlds collide when Henry makes plans to spend Saturday on the sofa watching a &quot;Gross Class Zero&quot; marathon &acirc;&euro;&rdquo; and his favorite characters come to life!"),
            Card(name: "GIMS: On the Record", imageName: "https://occ-0-38-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZQbaTOXUh5N6Qw323lgn9K5zD1dLser2yzjei_I5m_S6hTdgh2CzmHeUaBClV9oGegri8y7Gf9m7GijwnGuSqME322NYzKCZbpzGTt7TFqcmiyh9RLfDbZWXmM.jpg?r=6d5", released: "2020", bio: "Go backstage with beloved rap superstar Gims in the year leading up to his major 2019 Stade de France performance in this up-close documentary."),
            Card(name: "The Devil All The Time", imageName: "https://occ-0-38-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYzbmwfg6WrceEHt_Foj0GdcJgRIDf0yi9VvuacWnkX2zRdB0LDXSkq13a1WMIORqkmIfO_8NGegO5UxJpU6zpPoPhzbDXp99xvwK3ZxyjpFha-N5V39dyIOd7IymejfRGiczR3g8SiiY6APC05sFnzxzaLkayKNFdDB2r9WKMAFU4dGm4OxiQ.jpg?r=01f", released: "2020", bio: "Sinister characters converge around a young man devoted to protecting those he loves in a postwar backwoods town teeming with corruption and brutality."),
            Card(name: "Pets United", imageName: "https://occ-0-1952-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeYRKk7mHAV0v2zaeyftob7EfU8r1n2fDqKuyb2suXrZGqoCMpwwIjXNkI76CCpzDR1GQenPdR4eh_m4MLj23bvg3JMtBYqu7b5Nfs163XhLMpqL2z9SuH6APxk.jpg?r=879", released: "2020", bio: "A street-smart dog and a pampered cat join forces to lead a pack of unlikely heroes when their city is seized by its evil mayor &mdash; and his robot army."),
            Card(name: "Dad Wanted", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcTTC3zPwnmQ_vbyPP2D6CjHe1L_xTSJU8CxiNAmROFNlyIP_rfOwEPKd_-z1FFMe9es-XPQC8FXp9PWxN4Fwr2zyT3ae4uR9Vjr1cSVebF4MgJKQTwTH52Xrjc.jpg?r=1a2", released: "2020", bio: "What does a thrill-seeker tween girl do when her mom forbids her to enter a BMX race? Cast an actor with nothing to lose to play her approving dad."),
            Card(name: "The Babysitter: Killer Queen", imageName: "https://occ-0-1952-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRKYC8Z0gM69hlzYr5r2QKJpySAfim9dMWYSWA-BHAWwOQY6nhsjBJKXvx1mSmGUM_8qKKvZw_je2jdFrqPbfS4p3T078R_xWZZO0kda5u5hnXnUuVF8wopnZlE.jpg?r=345", released: "2020", bio: "Two years after Cole survived a satanic blood cult, he&#39;s living another nightmare: high school. And the demons from his past? Still making his life hell."),
            Card(name: "Cuties", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABa_hjv5C58zgBsw4OP-TvMJQwEQKclb5qr8KAAAjTxwYf6cjAnSQsf5AP_bzYwLB9pQDb3d-igD0HD0Sk1wGWErpZVO-iSW6jBfoU8c9b2MxYFbAsqYy0PL0WT8.jpg?r=64d", released: "2020", bio: "Eleven-year-old Amy starts to rebel against her conservative family&rsquo;s traditions when she becomes fascinated with a free-spirited dance crew."),
            Card(name: "The Social Dilemma", imageName: "https://occ-0-2430-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUybphDaTOAFPJjDzl1U7gj4yveXnO0Bc5ZxaWE_FwkH9jDIgwRewZ91goDn5IAKEAzmbszvRdBCN_w6DsPIfg3HToAR78Eqal8ExMJYJqAOOgO_WBOjy7ElGhU.jpg?r=288", released: "2020", bio: "This documentary-drama hybrid explores the dangerous human impact of social networking, with tech experts sounding the alarm on their own creations."),
            Card(name: "My Octopus Teacher", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbkY0SGDRG6b-X6smZYcIcrOu68XilnU9UxcvJdfwxCCnXSPx8WxMACrzEamMt577ZKMVInfm7HzXD8i3tJfGwuoCVT-N9DqtOhFbSeJ8was9hQ44nOuUt8MEo8.jpg?r=938", released: "2020", bio: "A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world."),
            Card(name: "Lingua Franca", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbFfkWgrmnqx77xIuXgjWIbgarzdYSuQN7C0jd2OyF5M1xclu8fWcAjwpZadepHIl8XQcjx5iXgVVgBeL_SFjDM69w.jpg?r=411", released: "2020", bio: "An undocumented trans woman seeking legal status in the US becomes romantically involved with the grandson of the elderly woman she cares for."),
            Card(name: "The Lost Husband", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQfhPOPN0vBPFbGCGOFiLNTJy_rRQnmRn84weNc3HvKu1GAcU3IJKIjX02wrgVOSZJ1w4_bWf-YKurC4x3SNUEQgfg.jpg?r=58b", released: "2020", bio: "Looking to start anew, a widow retreats with her children to her aunt&#39;s goat farm, where the ranch&#39;s manager helps her navigate country life and loss."),
            Card(name: "Night Comes On", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSln91LUBilw-2iStJwbsX882h3NSaat9NDluLzBF23ejNAlJKvFWvWWUXvyqvlRfByY55tQJ0YxiNLEfT3pOJVhjA.jpg?r=614", released: "2018", bio: "A teen fresh out of juvenile detention tries to rescue her sister from foster care in order to exact revenge on their father for their mother&#39;s murder."),
            Card(name: "Possession", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABedgzllwjBb44VpefzeNgvL8nuJxcBZJWaUGxfWEAyFqdxbPKrV03ThvaxCVxC9I6FgxBO-3mWW4xFmhDT9jGfK1wQ.jpg?r=1f9", released: "2002", bio: "As two guarded scholars research a secret affair between a pair of Victorian poets, they find themselves drawn in by the romance of their subjects."),
            Card(name: "Quantum of Solace", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABU1xV8JxO4jscDoELcC59ek88LfYws9Ownococa_ppd9zoxuHFtLEQeI_h7AhT4KJXTNztirq3VdfYii0ADm2xowTw.jpg?r=af5", released: "2008", bio: "Picking up an hour after the events of 2006&#39;s Casino Royale, this James Bond adventure finds 007 tracking a traitor who&#39;s infiltrated Britain&#39;s MI6."),
            Card(name: "Strange but True", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWMfJEmuddiCyb9UWdBsNsey422v0vPyJILJgWz9cxCtdhxKd_vZ8uBCYnYFmyt4NaptW-Ji8F9SG16DLNm49sBq5g.jpg?r=7a1", released: "2019", bio: "A young woman rattles her former boyfriend&rsquo;s family when she reveals she is pregnant with his child &mdash; despite his death five years ago."),
            Card(name: "We Summon the Darkness", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABatz95xbA3WSXjei-RAWMQJ_5qvqpfSxhAJa3xDlZ0wrnAlr4mJLsMhNp0FeaQWtQ0x5jvQr-A7JNVGQ_FLA_ZFrVg.jpg?r=b99", released: "2020", bio: "A night at a 1980s heavy metal concert hits a grisly note when new friends find themselves in the middle of a satanic murder spree."),
            Card(name: "The Young Messiah", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWItDgPkRZBRg58gEEDR1LfDrYEwTVww4a0lRp6GlFADTh0FouSwFrTUMRlzyGLpfA98nJMBA0Mw40Sf25y4ohA65w.jpg?r=4e6", released: "2016", bio: "Tormented by a demon and on the run from a Roman centurion, a 7-year-old Jesus and his parents, Mary and Joseph, flee Egypt for Nazareth."),
            Card(name: "A Girl Like Grace", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABV4YB7HaR5kHsHryCGlw6RMQDBkynpREz0yhWkCsxLXw9LTvjsvTN7iNrA0S1xMDcuLw67R-So4f7bbVhJ34MWsohg.jpg?r=60d", released: "2015", bio: "A 17-year-old girl living in a Mississippi trailer park with her troubled mom grapples with her sexuality, peer pressure and a devastating loss."),
            Card(name: "Freak Show", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSZPIbarPgTt-k2z9e5cSg6_VfGyKJj5IMkcvlYNLR5nT9YgqK09xavFd8MoFNdVj01Nj3QYJR3wKVvYj018PcBnSQ.jpg?r=08a", released: "2018", bio: "Forced to attend a new high school, a glamorous teen navigates hostile territory before taking a stand by running for homecoming queen."),
            Card(name: "1BR", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZB7UmqW6uZCHuEHlksF0o1VCqCXCWfBe1sge0uyRmw6eE2d0GbRIUpqjktH_pBEbt_2WTSdQt0S8UoqvV1_ntQBsw.jpg?r=40b", released: "2019", bio: "Seeking her independence, a young woman moves to Los Angeles and settles into a cozy apartment complex with a disturbing sense of community."),
            Card(name: "Afterschool", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVPl9ASPCm17yV90V1t7JmTPg6cIsbc0A2lK7PMoFbuv2H5YBebyQWKUUeYYKqoXaQW5kVbcv1Nya18fKa8Ym0-tHw.jpg?r=615", released: "2008", bio: "When a prep school loner films two classmates overdosing on cocaine, his footage plays a role in the emotional fallout within the school community."),
            Card(name: "I&#39;m Thinking of Ending Things", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSfxyK8VhBjL2dj6s2xoe4LJKEfK5xXDJjSj6Qbg3ib9ULUzZNH34TItsciUWGIbKAc1qu1dj10LXa-BpJQgenj-NfGgJ1ovviIiGyoObv5imS3mryg5g0BlDfc.jpg?r=d31", released: "2020", bio: "Nothing is as it seems when a woman experiencing misgivings about her new boyfriend joins him on a road trip to meet his parents at their remote farm."),
            Card(name: "Love, Guaranteed", imageName: "https://occ-0-2430-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVe7WPDoTYqK2elIhMrsoeHuDrNth6PiUTtFI-FaP9ZYOMSXgynA5hIzjF8fgZvnJqC5DwEF3iof7t-S5VxkbCAg_ZZWNXt15wFEC0lWTLDG_qfBedhABaBwf2w.jpg?r=57a", released: "2020", bio: "Sparks fly when a crusading but cash-strapped attorney takes on a charming client looking to sue a dating site that guarantees its users will find love."),
            Card(name: "Barbie Princess Adventure", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRY0PpTaSrUOpu4tMaCDsycG4ClIyNSe6vDSLXLTpLaORmqswSZBfAUyLk_mlyUE9Kt65-e3_J3EzKsV-LIwdna66Q.jpg?r=267", released: "2020", bio: "With new friends in a new kingdom, Barbie learns what it means to be herself when she trades places with a royal lookalike in this musical adventure."),
            Card(name: "The Boss Baby: Get That Baby!", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYijeVNKcrzBJLVL7L8fii1OYT-7pwnAPqU15o2idBgrBhRZcRnBep5bTw673JnBt7TWTDuX2FZ1QZiGxnLKvbiKMazRjggML4jLEiAbEtoLt320sm0ZhwuNXm5jdJhZzWmrDoU78za-KW7VTKn5C8hO4zOT.jpg?r=e5e", released: "2020", bio: "Think you&#39;ve got what it takes to be the boss? This interactive special puts your skills to the test and matches you up with one of 16 jobs at Baby Corp."),
            Card(name: "Santana", imageName: "https://occ-0-1952-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfXb-dHK9P3khmoIhr52RBUmRRAqvxLip05MnynGC3K4164FN7JSyu9tijKFwYQB39hzvBvxxT7cnVDytfTbbWHuySTnWj_PDWrDHYqkCh9RhE_L095NbM-CPPo.jpg?r=d08", released: "2020", bio: "Two brothers &mdash; one a narcotics agent and the other a general &mdash;&nbsp;finally discover the identity of the drug lord who murdered their parents decades ago."),
            Card(name: "Unknown Origins", imageName: "https://occ-0-1952-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXllfn684BqwHua2Hb-0ADRC7qObYVFo3WQlwnPxWiXcD3MD6fplRV54DsCJncQSyFUlfj4kSzgk_MufPbWCAgCyg2l_rZbo4bbXG9ATkl5YjOLRAZddfTkwq4E.jpg?r=7ce", released: "2020", bio: "A very chiseled but somber detective must find a serial killer who leaves clues that only his mentor&#39;s nerdy comics-loving son can decipher."),
            Card(name: "Making The Witcher", imageName: "https://occ-0-778-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABad5Z33sFcO4_QTDAOcPPHOK_8qvO3Mo4LFHYSdALgXzNpycyl5aBQqP1Z8gtbkZkt8ibMbatFXERM4LSCoW5qj8FQ88idVQ8R6d9iNz8fJKvc8QFkrumPNBYFQ.jpg?r=933", released: "2020", bio: "Journey into the extraordinary world of &quot;The Witcher&quot; &mdash; from casting the roles to Jaskier&#39;s catchy song &mdash; in this behind-the-scenes look at the series."),
            Card(name: "Rising Phoenix", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABe1lS7VkKFF7blJt8cSZbzqHVufinF_5xiF29x_TTVy0a2BKexMyXhJkQ6A6d-QC7pVXBhA6WoNYxbDMuiXv5uMBcgTBJVLis7ghP_T-Vm3SIy_2a6iQEmMOLWc.jpg?r=ddc", released: "2020", bio: "Elite athletes and insiders reflect on the Paralympic Games and examine how they impact a global understanding of disability, diversity and excellence."),
            Card(name: "Class of &#39;83", imageName: "https://occ-0-360-358.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABafnwVugxXI3QQG-dvW5_rugzDcz_oV4paKFy95mH2bvY6cClS7AJeGLGy5jt35zgFVCSwBUH3w9UIFnp_9egnaz2q6gH_zKqnbo38sgfBOzr2iKGwKiiKAelhs.jpg?r=cff", released: "2020", bio: "Demoted to an academy job, a cop trains five foolhardy students as assassins in his risky revenge plot against police corruption and the underworld."),
            Card(name: "The Sleepover", imageName: "https://occ-0-360-358.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZHMa8ZU_Mz9jtz8YCwgxGRrwNeQZu9wOyA5vZN2Hs6RFxYGL0OJsuYMLk9FRphpznO_-ZfINHzkrrdxcv5A_osGg-EPEwQ-Imqn5RWeFVZErmkD-keypEqz3UQ.jpg?r=6cc", released: "2020", bio: "What do you do if your parents are kidnapped by a crew of international thieves? You begin a wild overnight adventure &acirc;&euro;&rdquo; complete with spy gear."),
            Card(name: "The Crimes That Bind", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUIb6xli0vTgP8qliSc3oKAX3cfONtRd1KXzfT-kUApS8Dz9-E6W6ZqNiTASWreG0tKOmb9mdBEk9xRF1wvft-mzJ5eNZwYguy13V8LcW_ixkClXJ5f4twXIfkA.jpg?r=64d", released: "2020", bio: "When her son is accused of raping and trying to murder his ex-wife, Alicia embarks on a journey that will change her life forever."),
            Card(name: "John Was Trying to Contact Aliens", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSeW0lX_3Shr_V3v9wrvG45tiZ9icdsC7lymjDkXWX7bFjw7YxNnLsbtHtYLh4L1Cgg4qmJJDEksc0HwosDVx1kaFfQXTqx5RPK4c8rjvYXJey53D4XmY3Lx1mA.jpg?r=004", released: "2020", bio: "A rural electronics whiz broadcasts radio signals into space and monitors for signs of aliens, but makes a more important connection here on Earth."),
            Card(name: "Good Kisser", imageName: "https://occ-0-753-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfKNwFDZ92Fo3klC9YIw-g3RXXAI09R7HGIUslrq0-DMaabZlGiGXrS4MzyOWXVnLCZSZqay2WNVniPZrpfho6XgQA.jpg?r=3c8", released: "2019", bio: "Hoping to give their relationship a boost, Jenna and Kate arrange to spend an evening with a third woman, but things take a turn once the sparks fly."),
            Card(name: "Meet the In-Laws", imageName: "https://occ-0-56-55.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYG0RJ4oFkwcWYki1NbVbg38VNh7zZzoaePvR4XywAP3GF6XRcPJZccoX1rvXIKU-ObQOMM6iNPBE4NW5uMbSDqEeg.jpg?r=fb9", released: "2017", bio: "When their respective parents oppose their union, a newly engaged couple learns that the reasons for pushback run deeper than just tribal differences."),
            Card(name: "An Easy Girl", imageName: "https://occ-0-55-56.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABd-7Mop351oTaFpSczF4gAidFZm3ZY32gVWnP-OO5yl1wR69vqa5y-SlEtgZPGwPkr4TXpKJe7YVx9PyV8IQ2VG-Llzog_P-ZplE1X8EFz2cQm1mEHqQX-Mt5q0.jpg?r=4c9", released: "2019", bio: "A teen girl is drawn to her cousin&rsquo;s hedonistic lifestyle when they spend the summer together in Cannes as she learns about herself and her own values."),
            Card(name: "Octonauts &amp; the Caves of Sac Actun", imageName: "https://occ-0-2851-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABU83VHEqt_Qa5Y0PeA9rYupGQFWFneulX5ltEuRq43_QKscSj_ziyeo7hP0GyaKH-FZQszSgtO79ay03oCXw0I06seCZVP2tRTRnfxpWngqUDrXOQH4G-wRNaD4.jpg?r=825", released: "2020", bio: "The Octonauts embark on an underwater adventure, navigating a set of challenging caves to help a small octopus friend return home to the Caribbean Sea."),
            Card(name: "Gunjan Saxena: The Kargil Girl", imageName: "https://occ-0-300-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQ5PnV0JBorJCIiin5lQKWHGC_szQJ5zWEwzzAIHXJn0myucPyoIZE9YhpSbhCR-aCO9Ljo5sLz7pBCF7wD7mgY-kv_XfluA0VPNRXs1jrCeC0nDPNJrQXSdt0w.jpg?r=a85", released: "2020", bio: "Flight Lieutenant Gunjan Saxena makes history in her journey from aspiring aviator to India&rsquo;s first female combat pilot in the Kargil War."),
            Card(name: "Nigerian Prince", imageName: "https://occ-0-300-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTVkSRgaFQ1NfLZomn2rSCVxzEVPEi9oToaGpg8raTlzGLicUJYuE6QkeaBk2cYx73EuRcuxz-9nYur235JAOB5h1Q.jpg?r=1da", released: "2018", bio: "When a stubborn American teenager is sent to Nigeria by his mother, his cousin&#39;s scamming business becomes a viable option for securing a return flight."),
            Card(name: "Project Power", imageName: "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABW8o-aVMkcBQTXLHHjpuCzAi7YyBndAiT_LnXgM8Gn4MrU9scXXHoN9FUIv-GJ-8UpHEW1tfbexlMGLakT835dP0CA.jpg?r=5ae", released: "2020", bio: "An ex-soldier, a teen and a cop collide in New Orleans as they hunt for the source behind a dangerous new pill that grants users temporary superpowers."),
            Card(name: "Fearless", imageName: "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABT1mpi9E2jKto4GvdClZQHSfhI2P-Pt2tKBbCBr8_0yLw34POmmUacDMSxq_PnyyLdd-TXKzrtpJkZTDeniAhu9Ph7VbNKUxvGhN4DBpgKzJInB4gxsB99BxCY4.jpg?r=c21", released: "2020", bio: "A teen gamer is forced to level up to full-time babysitter when his favorite video game drops three superpowered infants from space into his backyard."),
            Card(name: "Rob Schneider: Asian Momma, Mexican Kids", imageName: "https://occ-0-753-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABScC3IiCtvp1uboxijzrZmKPAct0F1NTH7RTKo0It8LwRvAHHrMGvNfH-LgD7tbCyeCGlLICCawgldqQG-H40_kfysE8CNUf4W7h0cptQa85hiuNur3SmYJshhU.jpg?r=721", released: "2020", bio: "Former &quot;Saturday Night Live&quot; star Rob Schneider returns to the stage and shares his take on life, love and dinosaur dreams in this stand-up special."),
            Card(name: "Killing Hasselhoff", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQ_h2zVkCBrR4HEsOZdkfmkeWS-ak_u_fs2pLT1EfG8q2N-ZLFktvzEsnmub7ZVd576t5aFnuMAcSVAbw3WcW1IaYg.jpg?r=78d", released: "2017", bio: "In major debt to a loan shark, a nightclub owner who&#39;s entered in a celebrity death pool tries to murder a famous figure for half a million dollars."),
            Card(name: "Work It", imageName: "https://occ-0-1489-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdvO5igQ9XvYB399fYm03NU2fBCLXM66wBle_K8pHi3-Lpnl3tWTQfG-UFaGPdOMqpZMr-An9sh4ifI-prPZb_heouIG6qnOwIyAmQ_mcnvy85WFatoeQjG-gKY.jpg?r=d32", released: "2020", bio: "A brilliant but clumsy high school senior vows to get into her late father&rsquo;s alma mater by transforming herself and a misfit squad into dance champions."),
            Card(name: "The Magic School Bus Rides Again Kids In Space", imageName: "https://occ-0-1489-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbu3MWTmbbUHdM1-X1Jg-msG2NNSpsVY8Et7FcOxe2f-Vgye-VYENNVipxfMaPCnm6vVNExpti2liKS8c9DjFJQkEHZlkzu4iTvw2-1ww0phq8Z924_xvXLVCKM.jpg?r=b15", released: "2020", bio: "The Magic School Bus kids blast into orbit &mdash; and onto the International Space Station &mdash; only to find themselves on the run from a giant tardigrade!"),
            Card(name: "Stars in the Sky: A Hunting Story", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYXo3vPKH6WlxCONV--TUgdwsk6KuMrWe3f2nFYIg6GggvURtsuwbDE3bNW5611lIyDMjJFqBoXOaTAZGYcQJ7yZGw.jpg?r=708", released: "2018", bio: "This documentary follows a group of hunters as they grapple with the complexities, controversies, and contradictions of pursuing animals in the wild."),
            Card(name: "Diamonds in the Sky", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXhuqNcXXfsDPegExcm6r5jNlRi_l-0F7SxXpyAU23a4rmh9B-c4v9k0n5ncFPLMNjQPmZx4W2ncSprBFXXLMcalrg.jpg?r=360", released: "2018", bio: "Three families navigate uncertainty and struggle when cancer affects their lives and presents emotional challenges that test their bonds."),
            Card(name: "Sin City", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbXEqHFdBakLxYLFNFT7zr-noF9WCPAwrlkfMr86vnyhILkFuvMnjg2jUeLmNpQ1BVaObsmeLh8bq3pSJYD25j9j7g.jpg?r=885", released: "2019", bio: "A busy couple tries to give their love life a boost by taking an impromptu weekend trip only to find their relationship tested in unexpected ways."),
            Card(name: "Malibu Rescue: The Next Wave", imageName: "https://occ-0-2773-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABU7AUXhjbMnWyZ3uz3Adya8xdkDzolGkfhTvugpH02IU0_baBnE1nCu6lkVNHnFoiBEyCUhBNvnF-LeGiAVcmUHkimpjPNgStvbA0s35YJmNUXVR508rsFX0TQM.jpg?r=a24", released: "2020", bio: "As summer returns to Malibu, Team Flounder takes to the beach to host &mdash; and unexpectedly compete in &mdash; the International Beachmaster Competition."),
            Card(name: "Almost Love", imageName: "https://occ-0-2218-2219.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABce2Ryv4HOxVha22c1OSTyrgHp_CtJ1TcIMDKY7dt2JbpmXJx1qOC4o4MswL5GGUsLnTU7Efj_3bZkdl6NErv-o9Sg.jpg?r=20b", released: "2020", bio: "A close crew of striving New Yorkers experiences both joy and heartache in their romantic and professional lives."),
            Card(name: "Super Monsters: The New Class", imageName: "https://occ-0-114-116.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABb6ApH9G5PGXqOwV4jlGaxhlYdlD8VZpPLvQ8DMNltBZVsSI74mqmpcOZQ5_jt8gBP526ld5OSFdyWUcubfYCvNeBhsZZOZzlLyXLX_HBy-b4fln2jLR7g7xScY.jpg?r=33a", released: "2020", bio: "A new class of pint-sized preschoolers arrives at Pitchfork Pines, and the Super Monsters take their superpowers to the next level &acirc;&euro;&rdquo; the Purple Room!"),
            Card(name: "Raat Akeli Hai", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRgFWd9ynaYlHErd_k1WAztW61v-2M_yX12vVIjjAr5OLeTzt_1zTtjDZuwWTFSGBDzHY5cErY6kYBqHSr-CdKFKWRpvxpjYWON-cp7Ngad957MNPRkuBRHhsxI.jpg?r=ee4", released: "2020", bio: "When a newly married landlord is murdered, a misfit cop&rsquo;s investigation is complicated by the victim&rsquo;s secretive family and his own conflicted heart."),
            Card(name: "Sugar High", imageName: "https://occ-0-2430-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRQZu6Gw-H17kH17gV5NowC2PYOdKHKpV9naZlXkNcpwgoTkGWeXEow_QZk76tcbd9MeTOj4F-9HKBzTyz6m73GkuKgPWm15qU-BdTeswhoPqk5ylgz8j0BnXp8.jpg?r=62c", released: "2020", bio: "Talented sugar artists compete for $10,000 over two rounds of competition &mdash; candy and sugar sculpture &mdash; in this &quot;Sugar Rush&quot; spinoff special."),
            Card(name: "Seriously Single", imageName: "https://occ-0-2430-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfCbwlTjiOT0BTWRZbABdt70-rIZST30-FkBrIpAd_ShVGU3Bvk9EZ5i3DIZGwmzyqMhw3U36cVKy5xg025YYsGgMPSWw_mql-erZx9h-jKV-IDAtI0kvMOGgzU.jpg?r=494", released: "2020", bio: "While her free-living bestie urges her to embrace singlehood, a commitment-craving social media expert can&#39;t stop following the life of a former love."),
            Card(name: "Redemption", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTpLuI8Ags10LJetxdZd7zDcNVwO9vTJSkfEC9XksWiiNgnsKIlXdKSK_pX_0tzlzxHqkK1U0aJFEthtgWhHKsZcvA.jpg?r=073", released: "2019", bio: "Newly released from prison, a man returning to his girlfriend and their child subsequently learns about a dangerous debt taken by his late mother."),
            Card(name: "Shine Your Eyes", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRdYhJQ7xnkjT280AX8NNe48QnNNud_wlW1ScZRGU831WLKSIfSgT92IIQR8oC0wuGb-0rsB97Tq02w5fGtECqhjGw.jpg?r=096", released: "2020", bio: "A Nigerian musician travels to Brazil to search for his estranged brother, who is living a life very different than the one his family thought."),
            Card(name: "It&#39;s Her Day", imageName: "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSQZojgIkn4qNkZK6O7mpM8cwI45CPSYtAXN2XxD3KNGhobXtf44Vs3c0oUxVePGiFT_yj9uxkq8kCzmCW--LbhQGg.jpg?r=a3f", released: "2016", bio: "After a man promises his fianc&Atilde;&copy; a dream wedding, he must keep up with her outrageous requests to have the most lavish ceremony possible."),
            Card(name: "Animal Crackers", imageName: "https://occ-0-1091-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdQ3ObAShC0sMGrjMS0vG3G86Ci2fVoCXrv8HnSjEEU8lKBn4IznlyNlv2HBKH6CHMN5U1yIg0FKNB20JEOhEvhKenpW3xA_QbpMfHDK6EH4PE7ROp_pUpRZygk.jpg?r=87f", released: "2020", bio: "Enchanted animal crackers turn Owen into whatever shape he eats! But to save the family circus, he&#39;ll have to keep them out of his evil uncle&#39;s hands."),
            Card(name: "Offering to the Storm", imageName: "https://occ-0-38-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcPxeT-wPGOABI89Fx9KoYTOt_YnUglq7-IvJfjPsBbcFAPPtRreWoYdFptsKGX-lQwzZ_xl5U8LsKs4JKkMYDd5hwsdu3zwrnAMrLzeYGQynxJg3GtwfYwu9rk.jpg?r=299", released: "2020", bio: "Amaia investigates several suspicious infant deaths and horrific rituals. Meanwhile, people around her risk grave danger. Part 3 in the Baztan Trilogy."),
            Card(name: "Dragons: Rescue Riders: Secrets of the Songwing", imageName: "https://occ-0-38-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaW666MTN3JSreXMDYdS102dtKVK930L7GIoSVou3PUSocwHAgF8Gxpr1qHImCa7cVYdtl6TgTJK4yTVSVZtoL6Mng_jqk9Yf897avGs2eOkyA_OLeWp2lFjijw.jpg?r=1ad", released: "2020", bio: "When a musical dragon with a beautiful voice hypnotizes the dragons and people of Huttsgalor, the Rescue Riders have to find a way to break the spell.")
        ]
    }
    
//        let urlYourURL = URL (string: @"home_new.png")
//        avatarImageView.loadurl(url: urlYourURL!)
        //MoviesToCards()
    
}
//func MoviesToCards() -> [Card] {
//
//    //print(returnSessionMovies())
//
//    //wait(w_status: 2)
//    //sleep(4)
//    let movieList = returnSessionMovies()
//    var cardArray = [Card]()
//    for movie in movieList {
//        //let urlYourURL = URL (string: movie.image)
//        cardArray.append(Card(name: movie.title, imageName: "testSwipe", released: movie.released, bio: movie.synopsis))
//    }
//    //print(cardArray)
//    return cardArray
//
//
//}
extension UIImageView {
    func loadurl(url: URL) {
        DispatchQueue.global().async { [weak self] in
            if let data = try? Data(contentsOf: url) {
                if let image = UIImage(data: data) {
                    DispatchQueue.main.async {
                        self?.image = image
                    }
                }
            }
        }
    }
}
